#!/bin/bash
echo "Fixing indentation..."

for xml_file in data/training/*.xml; do
    base_name=$(basename "$xml_file" .xml)

    docker run --rm -i -u $(id -u) --volume "${PWD}:/src" --platform=linux/amd64/v8 klakegg/saxon:he xslt \
        -s:$xml_file \
        -xsl:xslt/fix-indentation.xsl \
        -o:data/training/$base_name.xml \
        $1

    if [ $? -ne 0 ]; then
        echo "Error: Saxon failed for $xml_file. Aborting script."
        exit 1
    fi

done