#!/bin/bash
set -e  # Abort on error

for xml_file in data/gold/*.xml; do
    base_name=$(basename "$xml_file" .xml)
    
    echo "Fixing indentation of $xml_file..."
    docker run --rm -i -u $(id -u) --volume "${PWD}:/src" --platform=linux/amd64/v8 klakegg/saxon:he xslt \
        -s:$xml_file \
        -xsl:xslt/fix-indentation.xsl \
        -o:docs/gold/$base_name.xml \
        $1

    if [ $? -ne 0 ]; then
        echo "Error: Saxon failed for $xml_file. Aborting script."
        exit 1
    fi

done