#!/bin/bash
set -e  # Abort on error

mkdir -p docs

echo "Generating Gold Viewer files..."

for xml_file in docs/gold/*.xml; do
    base_name=$(basename "$xml_file" .xml)
    docker run --rm -i -u $(id -u) --volume "${PWD}:/src" --platform=linux/amd64/v8 klakegg/saxon:he xslt \
        -s:$xml_file \
        -xsl:xslt/dataset-to-html.xsl \
        -o:docs/$base_name.html \
        $1

    if [ $? -ne 0 ]; then
        echo "Error: Saxon failed for $xml_file. Aborting script."
        exit 1
    fi
done
