name: XSLT Transformation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      saxon:
        image: klakegg/saxon:he
        options: --entrypoint /bin/sh

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Transform XML files
      run: /bin/bash .github/workflows/transform-files

    - name: Generate Directory Listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        FOLDER: docs

    - name: Deploy to GitHub Pages
      run: /bin/bash .github/workflows/deploy-to-pages
