name: XSLT Transformation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      saxon:
        image: klakegg/saxon:he
        options: --entrypoint /bin/sh

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Transform XML
      run: |
        # docker run --volume "${PWD}:/src" klakegg/saxon:he -s:/src/path/to/input.xml -xsl:/src/path/to/transform.xsl -o:/src/docs/output.xml
