name: XSLT Transformation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      saxon:
        image: klakegg/saxon:he
        options: --entrypoint /bin/sh

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Transform XML files
      run: |
        mkdir pages
        for xml_file in data/gold/*.xml; do
          base_name=$(basename "$xml_file" .xml)
          docker run --rm -i -u $(id -u) --volume "${PWD}:/src" klakegg/saxon:he xslt \
            -s:$xml_file \
            -xsl:.github/workflows/dataset-to-html.xslt \
            -o:docs/$base_name.html
        done

    - name: Generate Directory Listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        FOLDER: docs

    - name: Deploy to GitHub Pages
      run: |
        # Install gh-pages deployment tool
        sudo apt-get install -y python3-pip
        pip3 install ghp-import

        # Initialize the git repository and configure Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Add the HTML files from pages/
        git add docs/*.html

        # Commit the changes
        git commit -m "Deploy HTML files"

        # Push the changes to the gh-pages branch
        git push