name: Generate static html pages to view the gold standard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      saxon:
        image: klakegg/saxon:he
        options: --entrypoint /bin/sh

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Generate training data from gold
      run: .github/workflows/generate-training-data

    - name: Generate html files to view gold data
      run: .github/workflows/generate-gold-viewer

    - name: Generate Directory Listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        FOLDER: docs

    - name: Deploy to GitHub Pages
      run: .github/workflows/deploy-to-pages
