name: Generate static html pages to view the gold standard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      saxon:
        image: klakegg/saxon:he
        options: --entrypoint /bin/sh

    steps:
    - name: Install libxml2-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils

    - name: Check out source code
      uses: actions/checkout@v2

    - name: Generate training data from gold
      run: .github/workflows/generate-training-data

    - name: Fix indentation of training data
      run: .github/workflows/fix-indentation

    - name: Add validation error annotations
      run: .github/workflows/annotate-errors

    - name: Generate html files to view gold data
      run: .github/workflows/generate-gold-viewer

    - name: Generate Directory Listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        FOLDER: docs

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  
      run: .github/workflows/deploy-to-pages
